services:
  # Mongodb service
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  # Node js API service
  backend_service:
    build: ./backend
    container_name: backend_container
    ports:
      - '4000:4000'
    # volumes: # Removed bacause replacing node_modules
    #  - ./backend:/app
    #  - ./backend/node_modules:/app/node_modules
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

  frontend_service:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true


volumes:
  mongo_db: {}

